diff: true
require: 'ts-node/register'
extension:
  - ts
package: './package.json'
recursive: true
reporter: 'spec'
timeout: 600000
file:
  - './integration/provider-specific/local/setup.ts'
full-trace: true
bail: true